-- ============================================================
-- Bank Customer 360 Dashboard - Oracle DB Schema
-- Run this in your Oracle SQL Developer or SQL*Plus
-- ============================================================

-- Internal bank users (officers, tellers)
CREATE TABLE BANK_USERS (
  USER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USERNAME      VARCHAR2(50)  NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  FULL_NAME     VARCHAR2(100) NOT NULL,
  ROLE          VARCHAR2(20)  DEFAULT 'officer',
  CREATED_AT    DATE          DEFAULT SYSDATE
);

-- Bank customers
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FULL_NAME       VARCHAR2(100) NOT NULL,
  PHONE_NO        VARCHAR2(20)  UNIQUE,
  EMAIL           VARCHAR2(100),
  NATIONAL_ID     VARCHAR2(50),
  DATE_OF_BIRTH   DATE,
  ADDRESS         VARCHAR2(255),
  PROFILE_PICTURE BLOB,
  SIGNATURE_IMAGE BLOB,
  CREATED_AT      DATE DEFAULT SYSDATE
);

-- Bank accounts (one customer can have multiple)
CREATE TABLE ACCOUNTS (
  ACCOUNT_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUSTOMER_ID    NUMBER        NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
  ACCOUNT_NO     VARCHAR2(20)  NOT NULL UNIQUE,
  ACCOUNT_TYPE   VARCHAR2(30)  DEFAULT 'SAVINGS',
  BALANCE        NUMBER(18, 2) DEFAULT 0,
  ACCOUNT_STATUS VARCHAR2(20)  DEFAULT 'ACTIVE',
  BRANCH_CODE    VARCHAR2(10),
  OPEN_DATE      DATE          DEFAULT SYSDATE
);

-- Transactions
CREATE TABLE TRANSACTIONS (
  TXN_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACCOUNT_ID  NUMBER        NOT NULL REFERENCES ACCOUNTS(ACCOUNT_ID),
  TXN_DATE    DATE          DEFAULT SYSDATE,
  TXN_TYPE    VARCHAR2(10)  NOT NULL,  -- CREDIT / DEBIT
  AMOUNT      NUMBER(18, 2) NOT NULL,
  DESCRIPTION VARCHAR2(255),
  CHANNEL     VARCHAR2(30),            -- ATM, MOBILE, BRANCH, ONLINE
  STATUS      VARCHAR2(20)  DEFAULT 'SUCCESS'
);

-- Indexes for fast search
CREATE INDEX IDX_ACCOUNTS_NO   ON ACCOUNTS(ACCOUNT_NO);
CREATE INDEX IDX_CUSTOMERS_PHONE ON CUSTOMERS(PHONE_NO);
CREATE INDEX IDX_TXN_ACCOUNT   ON TRANSACTIONS(ACCOUNT_ID);
